/* Shared helpers used by index.html, post.html and admin.html */

const DRAFTS_KEY = "gadgetBlogDrafts";

function getDrafts() {
  try {
    return JSON.parse(localStorage.getItem(DRAFTS_KEY)) || [];
  } catch (e) {
    return [];
  }
}

function saveDraft(post) {
  const drafts = getDrafts().filter(p => p.id !== post.id);
  drafts.push(post);
  localStorage.setItem(DRAFTS_KEY, JSON.stringify(drafts));
}

function deleteDraft(id) {
  const drafts = getDrafts().filter(p => p.id !== id);
  localStorage.setItem(DRAFTS_KEY, JSON.stringify(drafts));
}

/* Drafts saved in this browser override a published post with the same id,
   and any new draft simply appears alongside the published ones. This lets
   you preview a post instantly, before ever touching posts.js. */
function loadAllPosts() {
  const published = (typeof POSTS !== "undefined") ? POSTS : [];
  const drafts = getDrafts();
  const byId = new Map();
  published.forEach(p => byId.set(p.id, p));
  drafts.forEach(p => byId.set(p.id, Object.assign({}, p, { isDraft: true })));
  return Array.from(byId.values()).sort((a, b) => (a.date < b.date ? 1 : -1));
}

function getPostById(id) {
  return loadAllPosts().find(p => p.id === id);
}

function formatDate(iso) {
  const d = new Date(iso + "T00:00:00");
  if (isNaN(d.getTime())) return iso;
  return d.toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" });
}

function escapeHtml(str) {
  return String(str || "").replace(/[&<>"']/g, c => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
  }[c]));
}

/* Categories are separate content sections (e.g. "Gadgets", "Sport items")
   that visitors reach through the "Categories" nav dropdown; every post
   belongs to exactly one. `prefix` is the relative path back to the blog
   root, same convention as disclosureHtml. */
function categoryHref(cat, prefix) {
  prefix = prefix || "";
  return `${prefix}index.html?cat=${encodeURIComponent(cat.id)}`;
}

function categoryName(id) {
  const cats = (typeof CATEGORIES !== "undefined") ? CATEGORIES : [];
  const found = cats.find(c => c.id === id);
  return found ? found.name : "";
}

function categoryMenuHtml(prefix, activeId) {
  const cats = (typeof CATEGORIES !== "undefined") ? CATEGORIES : [];
  if (!cats.length) {
    return `<span class="hint" style="display:block; padding:10px 14px; margin:0;">No categories yet</span>`;
  }
  return cats.map(c => `<a href="${categoryHref(c, prefix)}"${c.id === activeId ? ' class="active"' : ""}>${escapeHtml(c.name)}</a>`).join("");
}

/* Closes any open nav dropdown when the visitor clicks elsewhere on the
   page. The dropdown itself (open/close on click) works without this,
   since it's a plain <details>/<summary> — this just makes it dismiss
   automatically instead of only via a second click on the summary. */
function wireNavDropdowns() {
  document.addEventListener("click", e => {
    document.querySelectorAll("details.nav-dropdown[open]").forEach(d => {
      if (!d.contains(e.target)) d.removeAttribute("open");
    });
  });
}

/* Published posts get a real static page generated by build.js at
   posts/<id>.html (good for SEO and link previews). A draft only exists in
   this browser's local storage, so it can only ever be previewed through
   the dynamic post.html?id= page. */
function postHref(post) {
  return post.isDraft
    ? `post.html?id=${encodeURIComponent(post.id)}`
    : `posts/${encodeURIComponent(post.id)}.html`;
}

function postCardHtml(post) {
  return `
    <a class="card" href="${postHref(post)}">
      <div class="thumb">
        <img src="${escapeHtml(post.cover)}" alt="${escapeHtml(post.title)}" loading="lazy">
        <span class="badge">${escapeHtml(post.weekLabel)}${post.isDraft ? " · Draft" : ""}</span>
      </div>
      <div class="body">
        <div class="date">${formatDate(post.date)}</div>
        <h3>${escapeHtml(post.title)}</h3>
        <p class="excerpt">${escapeHtml(post.excerpt)}</p>
        <div class="footer-row">
          <span class="read">Read the list</span>
          <span class="btn-circle">&rarr;</span>
        </div>
      </div>
    </a>
  `;
}

function itemCardHtml(item) {
  const rankStr = String(item.rank).padStart(2, "0");
  return `
    <div class="item-card">
      <div class="item-rank">${rankStr}</div>
      <div class="item-thumb"><img src="${escapeHtml(item.image)}" alt="${escapeHtml(item.name)}" loading="lazy"></div>
      <div class="item-info">
        <h3>${escapeHtml(item.name)}</h3>
        <p>${escapeHtml(item.blurb)}</p>
        <div class="item-meta">
          ${item.price ? `<span class="item-price">${escapeHtml(item.price)}</span>` : ""}
          ${item.tag ? `<span class="pill-tag">${escapeHtml(item.tag)}</span>` : ""}
        </div>
      </div>
      <div class="item-action">
        <a class="btn btn-primary" href="${escapeHtml(item.link || "#")}" target="_blank" rel="sponsored noopener">View deal</a>
      </div>
    </div>
  `;
}

/* affiliate/FTC-style disclosure banner. `prefix` is the relative path back
   to the blog root ("" from blog/post.html, "../" from blog/posts/x.html). */
function disclosureHtml(prefix) {
  prefix = prefix || "";
  return `<p class="disclosure">This post contains affiliate links. If you buy something through one, we may earn a small commission at no extra cost to you. <a href="${prefix}disclosure.html">Learn more</a>.</p>`;
}

function postType(post) {
  return post.type === "review" ? "review" : "list";
}

/* Turns a block of plain text into paragraphs and bullet lists: blank lines
   separate paragraphs, and consecutive lines starting with "- " become a
   <ul>. Used for admin-authored review text instead of accepting raw HTML. */
function textBlockHtml(text) {
  const lines = String(text || "").split("\n");
  let html = "";
  let paraLines = [];
  let listItems = [];

  function flushPara() {
    if (paraLines.length) {
      html += `<p>${paraLines.map(escapeHtml).join("<br>")}</p>`;
      paraLines = [];
    }
  }
  function flushList() {
    if (listItems.length) {
      html += `<ul>${listItems.map(li => `<li>${escapeHtml(li)}</li>`).join("")}</ul>`;
      listItems = [];
    }
  }

  lines.forEach(rawLine => {
    const line = rawLine.trim();
    if (!line) { flushPara(); flushList(); return; }
    if (line.startsWith("- ")) { flushPara(); listItems.push(line.slice(2)); }
    else { flushList(); paraLines.push(line); }
  });
  flushPara();
  flushList();
  return html;
}

function productBoxHtml(product) {
  if (!product || (!product.name && !product.buyLink)) return "";
  return `
    <div class="product-box">
      ${product.image ? `<img src="${escapeHtml(product.image)}" alt="${escapeHtml(product.name || "")}">` : ""}
      <div class="product-box-info">
        ${product.name ? `<h3>${escapeHtml(product.name)}</h3>` : ""}
        ${product.price ? `<div class="product-box-price">${escapeHtml(product.price)}</div>` : ""}
        ${product.buyLink ? `<a class="btn btn-primary" href="${escapeHtml(product.buyLink)}" target="_blank" rel="sponsored noopener">View deal</a>` : ""}
      </div>
    </div>
  `;
}

/* Renders a "review" type post: intro, a product callout box, freeform
   sections (each with a heading), a pros/cons grid, a verdict, and an FAQ
   list — the long-form counterpart to itemCardHtml's ranked gadget cards. */
function reviewBodyHtml(post) {
  const sectionsHtml = (post.sections || []).map(s => `
    <h2>${escapeHtml(s.heading)}</h2>
    ${textBlockHtml(s.body)}
  `).join("");

  const hasPros = post.pros && post.pros.length;
  const hasCons = post.cons && post.cons.length;
  const prosConsHtml = (hasPros || hasCons) ? `
    <div class="pros-cons">
      ${hasPros ? `<div class="pros"><h3>Pros</h3><ul>${post.pros.map(p => `<li>${escapeHtml(p)}</li>`).join("")}</ul></div>` : ""}
      ${hasCons ? `<div class="cons"><h3>Cons</h3><ul>${post.cons.map(c => `<li>${escapeHtml(c)}</li>`).join("")}</ul></div>` : ""}
    </div>
  ` : "";

  const faqHtml = (post.faq && post.faq.length) ? `
    <h2>Frequently Asked Questions</h2>
    <div class="faq-list">
      ${post.faq.map(f => `<div class="faq-item"><h3>${escapeHtml(f.q)}</h3>${textBlockHtml(f.a)}</div>`).join("")}
    </div>
  ` : "";

  return `
    <div class="review-body">
      ${textBlockHtml(post.intro)}
      ${productBoxHtml(post.product)}
      ${sectionsHtml}
      ${prosConsHtml}
      ${post.verdict ? `<h2>Is It Worth Buying?</h2>${textBlockHtml(post.verdict)}` : ""}
      ${faqHtml}
    </div>
  `;
}

/* Renders whichever body a post needs — the ranked gadget list for "list"
   posts, or the long-form review layout for "review" posts. */
function postBodyHtml(post) {
  return postType(post) === "review"
    ? reviewBodyHtml(post)
    : `<div class="item-list">${(post.items || []).map(itemCardHtml).join("")}</div>`;
}
